apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-infra-config
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: home-infra
  path: ./k8s/infrastructure/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
