# k8s/clusters/home/kustomization.yaml
# This is the ROOT kustomization that ties everything together

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Build order via Flux Kustomizations: secrets → infrastructure → apps
resources:
  - ./secrets-kustomization.yaml
  - ./infra-kustomization.yaml
  - ./infra-config-kustomization.yaml
  - ./apps-kustomization.yaml
