apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/namespaces.yaml
  - ../base/storage-class.yaml
  - ../base/cert-manager-helmrelease.yaml
  - ../base/ingress-nginx-helmrelease.yaml
  - ../base/metallb-helmrelease.yaml
